{% set version = "1.22.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-broom.helpers
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broom.helpers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broom.helpers/broom.helpers_{{ version }}.tar.gz
  sha256: 16245642d70558a726bd2433d99d89996b9d230272d5042e816e14c1b1831f15

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=0.8
    - r-cards
    - r-cli
    - r-dplyr >=1.1.0
    - r-labelled
    - r-lifecycle
    - r-purrr
    - r-rlang >=1.0.1
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-broom >=0.8
    - r-cards
    - r-cli
    - r-dplyr >=1.1.0
    - r-labelled
    - r-lifecycle
    - r-purrr
    - r-rlang >=1.0.1
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('broom.helpers')"           # [not win]
    - "\"%R%\" -e \"library('broom.helpers')\""  # [win]

about:
  home: https://larmarange.github.io/broom.helpers/
  license: GPL-3.0-or-later
  summary: Provides suite of functions to work with regression model 'broom::tidy()' tibbles.  The suite includes functions to group regression model terms by variable, insert reference and header rows for categorical variables, add variable labels, and more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
